version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker pull centos:6
      - run: docker build -t centos:6-devel .
      - run: mkdir -p rpmbuild/SOURCES
      - run: curl http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz -o rpmbuild/SOURCES/yasm-1.3.0.tar.gz
      - run: docker run -it --rm -v ${PWD}/rpmbuild:/root/rpmbuild centos:6-devel chown -R root:root /root/rpmbuild
      - run: docker run -it --rm -v ${PWD}/rpmbuild:/root/rpmbuild centos:6-devel rpmbuild -ba /root/rpmbuild/SPECS/yasm.spec
  # build:
  #   docker:
  #     - image: circleci/node:9
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - run: docker pull centos:6
  #     - run: docker build -t centos:6-devel .
  #     - run: mkdir -p rpmbuild/SOURCES
  #     - run: curl http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz -o rpmbuild/SOURCES/yasm-1.3.0.tar.gz
  #     - run: docker run -it --rm -v ${PWD}/rpmbuild:/root/rpmbuild centos:6-devel chown -R root:root /root/rpmbuild
  #     - run: ls -lR ./rpmbuild
  #     - run: docker run -it --rm -v ${PWD}/rpmbuild:/root/rpmbuild centos:6-devel ls -lR /root/rpmbuild
  #     - run: docker run -it --rm -v ${PWD}/rpmbuild:/root/rpmbuild centos:6-devel rpmbuild -ba /root/rpmbuild/SPECS/yasm.spec
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
